# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumb"

# UI configs
title: "Allie Braun Photography"
subtitle: "Capturing the best moments"
author:  "Allie Braun"
header:
 title: "Allie Braun"
 subtitle: "Photography"
footer:
 name: "Hi! I'm Alexandria blah blah blah "
 bio: "blah blah blah blah blah blah blah blah blah blah"
social_urls:
  instagram: "https://www.instagram.com/alliebraunphotography"
  facebook: "https://www.facebook.com/profile.php?id=61567561535773"


theme: jekyll-theme-slate
